apiVersion: "kubeflow.org/v1alpha1"
kind: "MXJob"
metadata:
  name: "gpu-dist-job"
spec:
  jobMode: "dist"
  replicaSpecs:
    - replicas: 1
      mxReplicaType: SCHEDULER
      PsRootPort: 9000
      template:
        spec:
          containers:
            - image: jzp1025/mxnet:gpu_sleep
              name: mxnet
              workingDir: "/incubator-mxnet/example/image-classification"
              resources:
                limits:
                  nvidia.com/gpu: 1
          restartPolicy: OnFailure
    - replicas: 2 
      mxReplicaType: SERVER
      template:
        spec:
          containers:
            - image: jzp1025/mxnet:gpu_sleep
              name: mxnet
              workingDir: "/incubator-mxnet/example/image-classification"
              resources:
                limits:
                  nvidia.com/gpu: 1
          restartPolicy: OnFailure
    - replicas: 2
      mxReplicaType: WORKER
      template:
        spec:
          containers:
            - image: jzp1025/mxnet:gpu_sleep
              name: mxnet
              workingDir: "/incubator-mxnet/example/image-classification"
              resources:
                limits:
                  nvidia.com/gpu: 1
          restartPolicy: OnFailure
